sudo: false
language: python
python:
  - 2.6
  - 2.7
  - 3.6
cache:
  pip: true
install:
  - pip install coverage mdp
script:
  - nosetests --with-coverage --cover-branches
after_success:
  - bash <(curl -s https://codecov.io/bash)
