name: build

on: [push, pull_request]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        python-version: ['3.7', '3.8', '3.9', '3.10',  '3.11']
        include:
        - os: ubuntu-20.04
          python-version: '2.7'
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install coverage pytest-cov flake8 scikit-learn
    - name: Test
      run: |
        pytest --cov=. --cov-branch --cov-report=xml -v .
        flake8 --ignore E402,W503,W504 --exclude doc/conf.py .
    - uses: codecov/codecov-action@v1
